-- ==============================================================================
-- MAIN DAIRY MODULE SUPABASE MIGRATION SCRIPT
-- Run this script in your Supabase SQL Editor: Dashboard -> SQL Editor -> New Query
-- ==============================================================================

-- 1. Main Dairies (Plants / Chilling Centers to which bulk milk is sold)
CREATE TABLE IF NOT EXISTS main_dairies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dairy_no INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    mobile VARCHAR(20),
    email VARCHAR(100),
    village VARCHAR(255),
    animal_type VARCHAR(50) DEFAULT 'Cow',
    address TEXT,
    opening_balance NUMERIC(12,2) DEFAULT 0.00,
    current_balance NUMERIC(12,2) DEFAULT 0.00,
    status BOOLEAN DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure columns exist if table was already created earlier:
ALTER TABLE main_dairies ADD COLUMN IF NOT EXISTS dairy_no INT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE main_dairies ADD COLUMN IF NOT EXISTS village VARCHAR(255);
ALTER TABLE main_dairies ADD COLUMN IF NOT EXISTS animal_type VARCHAR(50) DEFAULT 'Cow';

-- Ensure dairy_no sequence starts from 1 and increments sequentially
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relkind = 'S' AND relname LIKE '%main_dairies_dairy_no%') THEN
        PERFORM setval(pg_get_serial_sequence('main_dairies', 'dairy_no'), COALESCE((SELECT MAX(dairy_no) FROM main_dairies), 0) + 1, false);
    END IF;
END $$;


-- 2. Main Dairy Rate Configs (Fat/SNF Rate Chart for Main Dairy)
CREATE TABLE IF NOT EXISTS main_dairy_rate_configs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    animal_type VARCHAR(50) NOT NULL, -- 'Cow Milk' or 'Buffalo Milk'
    rate_type VARCHAR(50) DEFAULT 'Increase', -- 'Increase' or 'Decrease'
    base_fat NUMERIC(5,2) NOT NULL,
    base_snf NUMERIC(5,2) NOT NULL,
    base_rate NUMERIC(8,2) NOT NULL,
    fat_rate NUMERIC(8,2) NOT NULL DEFAULT 0.00,
    snf_rate NUMERIC(8,2) NOT NULL DEFAULT 0.00,
    fat_point NUMERIC(5,2) DEFAULT 0.1,
    snf_point NUMERIC(5,2) DEFAULT 0.1,
    fat_range_from NUMERIC(5,2) DEFAULT 0.00,
    fat_range_to NUMERIC(5,2) DEFAULT 15.00,
    snf_range_from NUMERIC(5,2) DEFAULT 0.00,
    snf_range_to NUMERIC(5,2) DEFAULT 15.00,
    effective_date DATE NOT NULL DEFAULT CURRENT_DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure columns exist if table was already created earlier:
ALTER TABLE main_dairy_rate_configs ADD COLUMN IF NOT EXISTS fat_point NUMERIC(5,2) DEFAULT 0.1;
ALTER TABLE main_dairy_rate_configs ADD COLUMN IF NOT EXISTS snf_point NUMERIC(5,2) DEFAULT 0.1;

-- 3. Main Dairy Milk Collections / Dispatches
CREATE TABLE IF NOT EXISTS main_dairy_collections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    main_dairy_id UUID REFERENCES main_dairies(id) ON DELETE CASCADE,
    collection_date DATE NOT NULL DEFAULT CURRENT_DATE,
    shift VARCHAR(20) NOT NULL, -- 'Morning' or 'Evening'
    milk_type VARCHAR(50) NOT NULL, -- 'Cow Milk' or 'Buffalo Milk'
    quantity NUMERIC(10,2) NOT NULL,
    fat NUMERIC(5,2) NOT NULL,
    snf NUMERIC(5,2) NOT NULL,
    rate NUMERIC(8,2) NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    payment_status VARCHAR(50) DEFAULT 'Pending',
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Main Dairy Payments (Payments received from Main Dairy)
CREATE TABLE IF NOT EXISTS main_dairy_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    main_dairy_id UUID REFERENCES main_dairies(id) ON DELETE CASCADE,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC(12,2) NOT NULL,
    payment_mode VARCHAR(50) DEFAULT 'Bank Transfer',
    reference_no VARCHAR(100),
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. DISABLE ROW LEVEL SECURITY (RLS) FOR FULL APP ACCESS
ALTER TABLE main_dairies DISABLE ROW LEVEL SECURITY;
ALTER TABLE main_dairy_rate_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE main_dairy_collections DISABLE ROW LEVEL SECURITY;
ALTER TABLE main_dairy_payments DISABLE ROW LEVEL SECURITY;

-- 6. Trigger to update main_dairies balance automatically on dispatch/payment
CREATE OR REPLACE FUNCTION update_main_dairy_balance()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        IF (TG_TABLE_NAME = 'main_dairy_collections') THEN
            UPDATE main_dairies SET current_balance = current_balance + NEW.total_amount WHERE id = NEW.main_dairy_id;
        ELSIF (TG_TABLE_NAME = 'main_dairy_payments') THEN
            UPDATE main_dairies SET current_balance = current_balance - NEW.amount WHERE id = NEW.main_dairy_id;
        END IF;
    ELSIF (TG_OP = 'DELETE') THEN
        IF (TG_TABLE_NAME = 'main_dairy_collections') THEN
            UPDATE main_dairies SET current_balance = current_balance - OLD.total_amount WHERE id = OLD.main_dairy_id;
        ELSIF (TG_TABLE_NAME = 'main_dairy_payments') THEN
            UPDATE main_dairies SET current_balance = current_balance + OLD.amount WHERE id = OLD.main_dairy_id;
        END IF;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_main_dairy_collection_balance ON main_dairy_collections;
CREATE TRIGGER trg_main_dairy_collection_balance
AFTER INSERT OR DELETE ON main_dairy_collections
FOR EACH ROW EXECUTE FUNCTION update_main_dairy_balance();

DROP TRIGGER IF EXISTS trg_main_dairy_payment_balance ON main_dairy_payments;
CREATE TRIGGER trg_main_dairy_payment_balance
AFTER INSERT OR DELETE ON main_dairy_payments
FOR EACH ROW EXECUTE FUNCTION update_main_dairy_balance();
