import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../providers/stock_report_provider.dart';
import '../providers/settings_provider.dart';
import '../services/translations.dart';
import '../providers/language_provider.dart';
import '../providers/display_mode_provider.dart';

class StockReportScreen extends ConsumerWidget {
  const StockReportScreen({super.key});

  Future<void> _generatePdf(BuildContext context, StockReportData data, DateTime start, DateTime end, dynamic settings) async {
    final pdf = pw.Document();

    final dairyName = settings?.dairyName ?? 'Shree Ganesh Dairy';
    final ownerName = settings?.ownerName ?? 'Owner Name';
    final phone = settings?.mobile ?? '1234567890';
    final address = settings?.address ?? 'Dairy Address';

    final dateStr = '${DateFormat('dd/MM/yyyy').format(start)} to ${DateFormat('dd/MM/yyyy').format(end)}';

    
    pw.MemoryImage? logoImage;
    if (settings?.logoBytes != null) {
      logoImage = pw.MemoryImage(settings!.logoBytes!);
    }
    
    pw.Widget _buildHeader() {
      return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        if (logoImage != null)
          pw.Container(width: 60, height: 60, child: pw.Image(logoImage)),
        if (logoImage == null)
          pw.SizedBox(width: 60),
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [

            pw.Text(dairyName, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
            pw.SizedBox(height: 4),
            pw.Text('Owner: $ownerName | Phone: $phone'),
            pw.Text('Address: $address'),
            pw.SizedBox(height: 12),
            pw.Text('STOCK MOVEMENT & VALUATION REPORT', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, decoration: pw.TextDecoration.underline)),
            pw.Text('Period: $dateStr'),
            pw.SizedBox(height: 16),
          
            ],
          ),
        ),
        pw.SizedBox(width: 60),
      ],
    );
    }

    final headers = ['Sr.No', 'Product Name', 'Total IN (Qty)', 'Total OUT (Qty)', 'Current Stock', 'Total Value (Rs)'];
    
    int srNo = 1;
    final tableData = data.entries.map((e) => [
      (srNo++).toString(),
      e.productName,
      e.totalIn.toStringAsFixed(2),
      e.totalOut.toStringAsFixed(2),
      e.currentStock.toStringAsFixed(2),
      e.stockValue.toStringAsFixed(2)
    ]).toList();

    tableData.add(['', 'GRAND TOTAL VALUATION', '', '', '', data.grandTotalValue.toStringAsFixed(2)]);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            _buildHeader(),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              headers: headers,
              data: tableData,
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey900),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignments: {
                0: pw.Alignment.center,
                1: pw.Alignment.centerLeft,
                2: pw.Alignment.centerRight,
                3: pw.Alignment.centerRight,
                4: pw.Alignment.centerRight,
                5: pw.Alignment.centerRight,
              },
              border: pw.TableBorder.all(color: PdfColors.grey, width: 0.5),
            ),
            pw.SizedBox(height: 32),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Report Generated On: ${DateFormat('dd/MM/yyyy hh:mm a').format(DateTime.now())}', style: const pw.TextStyle(fontSize: 9)),
                pw.Text('Generated By: $dairyName', style: const pw.TextStyle(fontSize: 9)),
              ]
            )
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Stock_Report.pdf',
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final reportAsync = ref.watch(stockReportProvider);
    final notifier = ref.watch(stockReportProvider.notifier);
    final settingsAsync = ref.watch(settingsProvider);
    ref.watch(languageProvider);
    final displayMode = ref.watch(displayModeProvider);
    final isMobile = displayMode == DisplayMode.mobile || MediaQuery.of(context).size.width < 700;

    return Scaffold(
      appBar: AppBar(
        title: Text('Stock Report'.tr, style: const TextStyle(color: Colors.black87)),
        backgroundColor: Colors.white,
        elevation: 1,
        iconTheme: const IconThemeData(color: Colors.black87),
      ),
      body: Column(
        children: [
          // Filter Bar
          Container(
            padding: const EdgeInsets.all(16),
            color: Colors.white,
            child: isMobile
                ? Column(
                    children: [
                      InkWell(
                        onTap: () async {
                          final picked = await showDateRangePicker(
                            context: context,
                            firstDate: DateTime(2020),
                            lastDate: DateTime.now(),
                            initialDateRange: DateTimeRange(start: notifier.startDate, end: notifier.endDate),
                          );
                          if (picked != null) {
                            notifier.setDateRange(picked.start, picked.end);
                          }
                        },
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                          decoration: BoxDecoration(border: Border.all(color: Colors.grey), borderRadius: BorderRadius.circular(8)),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              const Icon(Icons.calendar_month, color: Colors.blue),
                              const SizedBox(width: 12),
                              Text(
                                '${DateFormat('dd/MM/yyyy').format(notifier.startDate)}  →  ${DateFormat('dd/MM/yyyy').format(notifier.endDate)}',
                                style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: 12),
                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton.icon(
                          icon: const Icon(Icons.picture_as_pdf),
                          label: Text('GENERATE PDF / PRINT'.tr),
                          style: ElevatedButton.styleFrom(backgroundColor: Colors.black87, foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(vertical: 14)),
                          onPressed: () {
                            if (reportAsync.hasValue) {
                              _generatePdf(context, reportAsync.value!, notifier.startDate, notifier.endDate, settingsAsync.value);
                            }
                          },
                        ),
                      ),
                    ],
                  )
                : Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      InkWell(
                        onTap: () async {
                          final picked = await showDateRangePicker(
                            context: context,
                            firstDate: DateTime(2020),
                            lastDate: DateTime.now(),
                            initialDateRange: DateTimeRange(start: notifier.startDate, end: notifier.endDate),
                          );
                          if (picked != null) {
                            notifier.setDateRange(picked.start, picked.end);
                          }
                        },
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                          decoration: BoxDecoration(border: Border.all(color: Colors.grey), borderRadius: BorderRadius.circular(8)),
                          child: Row(
                            children: [
                              const Icon(Icons.calendar_month, color: Colors.blue),
                              const SizedBox(width: 12),
                              Text(
                                '${DateFormat('dd/MM/yyyy').format(notifier.startDate)}  →  ${DateFormat('dd/MM/yyyy').format(notifier.endDate)}',
                                style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(width: 24),
                      ElevatedButton.icon(
                        icon: const Icon(Icons.picture_as_pdf),
                        label: Text('GENERATE PDF / PRINT'.tr),
                        style: ElevatedButton.styleFrom(backgroundColor: Colors.black87, foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16)),
                        onPressed: () {
                          if (reportAsync.hasValue) {
                            _generatePdf(context, reportAsync.value!, notifier.startDate, notifier.endDate, settingsAsync.value);
                          }
                        },
                      ),
                    ],
                  ),
          ),
          
          Expanded(
            child: reportAsync.when(
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (e, st) => Center(child: Text('${'Error'.tr}: $e')),
              data: (data) {
                if (data.entries.isEmpty) return Center(child: Text('No active products found.'.tr));

                return Padding(
                  padding: EdgeInsets.all(isMobile ? 12.0 : 24.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      isMobile
                          ? Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                Text('Current Stock Valuation'.tr, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                                const SizedBox(height: 8),
                                Container(
                                  padding: const EdgeInsets.all(12),
                                  decoration: BoxDecoration(color: Colors.green.shade50, borderRadius: BorderRadius.circular(8)),
                                  child: Text('${"TOTAL VALUE".tr}: ₹${data.grandTotalValue.toStringAsFixed(2)}', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.green.shade900)),
                                ),
                              ],
                            )
                          : Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text('Current Stock Valuation'.tr, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                                Container(
                                  padding: const EdgeInsets.all(12),
                                  decoration: BoxDecoration(color: Colors.green.shade50, borderRadius: BorderRadius.circular(8)),
                                  child: Text('${"TOTAL VALUE".tr}: ₹${data.grandTotalValue.toStringAsFixed(2)}', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.green.shade900)),
                                ),
                              ],
                            ),
                      const SizedBox(height: 16),
                      Expanded(
                        child: Card(
                          elevation: 2,
                          child: SingleChildScrollView(
                            child: SingleChildScrollView(
                              scrollDirection: Axis.horizontal,
                              child: DataTable(
                                headingRowColor: MaterialStateProperty.all(Colors.grey.shade100),
                                columns: [
                                  DataColumn(label: Text('Product'.tr, style: const TextStyle(fontWeight: FontWeight.bold))),
                                  DataColumn(label: Text('Total IN'.tr, style: const TextStyle(fontWeight: FontWeight.bold))),
                                  DataColumn(label: Text('Total OUT'.tr, style: const TextStyle(fontWeight: FontWeight.bold))),
                                  DataColumn(label: Text('Current Stock'.tr, style: const TextStyle(fontWeight: FontWeight.bold))),
                                  DataColumn(label: Text('Value (₹)'.tr, style: const TextStyle(fontWeight: FontWeight.bold))),
                                ],
                                rows: data.entries.map((e) => DataRow(
                                  cells: [
                                    DataCell(Text(e.productName, style: const TextStyle(fontWeight: FontWeight.bold))),
                                    DataCell(Text(e.totalIn.toStringAsFixed(2), style: const TextStyle(color: Colors.green))),
                                    DataCell(Text(e.totalOut.toStringAsFixed(2), style: const TextStyle(color: Colors.red))),
                                    DataCell(Text(e.currentStock.toStringAsFixed(2), style: const TextStyle(fontWeight: FontWeight.bold))),
                                    DataCell(Text(e.stockValue.toStringAsFixed(2))),
                                  ]
                                )).toList(),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                );
              }
            ),
          )
        ],
      ),
    );
  }
}
